name: 'dependabot-pr-parser'
description: 'Extracts information about a Dependabot PR from its title.'
inputs:
  pr_title:
    description: 'The title of the PR.'
    required: true
  package_wildcard_expressions:
    description: 'JSON-formatted list of wildcard expressions used to flag particular dependencies (e.g. enabled for auto-merging).'
    required: false
    default: '[]'
  verbose_mode:
    description: 'When "True", runs with additional logging'
    required: false
    default: 'False'
outputs:
  dependency_name:
    description: 'The name of the dependency.'
  version_from:
    description: 'The version of the dependency being updated from.'
  version_to:
    description: 'The version of the dependency being updated to.'
  folder:
    description: 'The folder where the dependency is updated.'
  update_type:
    description: 'The type of update (major, minor, patch).'
  is_matching_package:
    description: 'Flags whether the dependency matched any of the provided package name wildcard patterns'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - -Title
    - ${{inputs.pr_title}}
    - -PackageWildCardExpressions
    - ${{inputs.package_wildcard_expressions}}
    - -Verbose:$${{inputs.verbose_mode}}